name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -f docker/Dockerfile.dev -t api-pi:latest .

    - name: Run tests inside Docker
      run: |
        docker run --rm api-pi:latest pytest --cov=app --cov-report=term --cov-report=html tests/
